version: '3.3'

services:
  web:
    build: .
    container_name: laravel-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
